apiVersion: v1
kind: Service
metadata:
  name: appsmith-backend
  namespace: appsmith
  labels:
    app: appsmith-backend
spec:
  type: ClusterIP
  selector:
    app: appsmith-backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http

