apiVersion: v1
kind: Service
metadata:
  name: appsmith-frontend
  namespace: appsmith
  labels:
    app: appsmith-frontend
spec:
  type: ClusterIP
  selector:
    app: appsmith-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http

